### ISSUE TITLE
Split the code in multiple files

### ISSUE THREAD

**Issue by SuperFola** [Wafelack/yarpm#2]
Hi there (it's a me, again)

The project might benefit from being splitted into multiple files, eg one to handle package updating, another for installing packages, etc.

This way contributing will be easier.

Also maybe adding a `tests/` directory to fake tests and ensure that every functionnality works as intended would be great maybe

**Comment by Wafelack** [comment]
I written tests and splited files in 3 categories: initialisation, package management, sources management
